site_name: movies
site_description: Its all about a Weissman score > 5.0
repo_url: https://github.com/godlark/movies
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/godlark">godlark</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
